import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,mkdir} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {randomUUID} from 'node:crypto';
import {StudioService} from '../server/studio-service.mjs';
import {MiniMaxCode,minimaxArguments} from '../server/minimax-code.mjs';
import {inspectAudio} from '../server/studio-media.mjs';
import {emptyDraft,musicRequest,handoffPrompt,validateLyricsOutput} from '../dist/studio-core.mjs';
import {createServer} from '../server/http.mjs';
const draft=()=>({...emptyDraft(),title:'旧车铃',idea:'多年后回家发现父亲还留着我的旧自行车',lyrics:'[Verse]\n旧车还停在院子里面\n[Chorus]\n你等我回家的那些天'});
const lyrics=()=>({title:'院子里的车铃',lyrics:'[Verse]\n那辆旧车还在墙边\n[Chorus]\n才懂你等我回家的那些天',direction:'从回家的细节走向迟来的理解，不强行煽情。'});
function wav(){const samples=16000,bytes=samples*2,b=Buffer.alloc(44+bytes);b.write('RIFF');b.writeUInt32LE(36+bytes,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(8000,24);b.writeUInt32LE(16000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(bytes,40);for(let i=0;i<samples;i++)b.writeInt16LE(Math.round(Math.sin(i*.12)*10000),44+i*2);return b;}
const gate=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
async function setup(options={}){return new StudioService({directory:await mkdtemp(join(tmpdir(),'sonara-studio-')),codex:{status:async()=>({ready:true}),generate:async()=>lyrics()},minimax:{status:async()=>({available:true}),generate:async()=>lyrics(),music:async()=>({data:wav(),note:'Test double, not a generated song'})},...options}).init();}
async function music(s,p){const result=await s.prepare(p.id,{requestId:randomUUID(),revision:p.revision,type:'music'});return result.tasks.at(-1);}
test('a music task freezes confirmed lyrics and emotional direction while later drafts remain editable',async()=>{
  const s=await setup(),p=await s.create({draft:draft()}),t=await music(s,p);const updated=await s.save(p.id,{revision:p.revision,draft:{...p.draft,emotionPeak:'更开阔',lyrics:'新歌词有不同的故事与表达',revisionNotes:'副歌更有力量'}});
  assert.equal(t.snapshot.lyrics,p.draft.lyrics);assert.equal(updated.tasks[0].snapshot.emotionPeak,p.draft.emotionPeak);assert.equal(updated.history.length,1);
  const request=musicRequest(updated,updated.tasks[0]);assert.equal(request.lyrics,p.draft.lyrics);assert.equal(request.direction.revisionNotes,'');assert.equal(updated.draft.revisionNotes,'副歌更有力量');assert.equal(request.constraints.exactMelodyPreservation,false);assert.match(handoffPrompt(updated,t),/一次只发起一个/);
  await assert.rejects(s.save(p.id,{revision:1,draft:p.draft}),e=>e.status===409);await s.close();
});
test('instrumental handoffs omit all lyrics and explicitly request no voice',async()=>{const s=await setup(),p=await s.create({draft:{...draft(),mode:'instrumental'}}),t=await music(s,p),r=musicRequest(p,t);assert.equal(r.lyrics,'');assert.match(r.direction.voice,/无演唱/);await assert.rejects(s.prepare(p.id,{type:'lyrics',provider:'codex',revision:p.revision,requestId:randomUUID()}));await s.close();});
test('lyrics are a separate proposal, never silently replace user text, and repeated requests are idempotent',async()=>{let calls=0;const s=await setup({codex:{status:async()=>({ready:true}),generate:async()=>{calls++;return lyrics();}}}),p=await s.create({draft:draft()}),request={type:'lyrics',provider:'codex',revision:p.revision,requestId:randomUUID()};await Promise.all([s.prepare(p.id,request),s.prepare(p.id,request)]);await s.tail;const result=s.get(p.id);assert.equal(calls,1);assert.equal(result.tasks.length,1);assert.equal(result.draft.lyrics,p.draft.lyrics);assert.equal(result.tasks[0].output.lyrics,lyrics().lyrics);await assert.rejects(s.prepare(p.id,{...request,provider:'minimax-code'}),e=>e.status===409);await s.close();});
test('music is not submitted until explicit execution and a task cannot be submitted twice',async()=>{let calls=0;const s=await setup({minimax:{status:async()=>({available:true}),music:async()=>{calls++;return {data:wav()};}}}),p=await s.create({draft:draft()}),t=await music(s,p);assert.equal(calls,0);await Promise.all([s.run(p.id,t.id),s.run(p.id,t.id)]);await s.tail;assert.equal(calls,1);assert.equal(s.get(p.id).tasks[0].state,'succeeded');assert.equal((await s.audio(p.id,t.id)).data.length,wav().length);await s.run(p.id,t.id);assert.equal(calls,1);await s.close();});
test('invalid files never become completed songs and manually imported audio cannot overwrite a take',async()=>{const s=await setup(),p=await s.create({draft:draft()}),t=await music(s,p);for(const data of [Buffer.from('ID3'.padEnd(1000,'x')),Buffer.from('<html>oops</html>'),wav().subarray(0,100)])await assert.rejects(s.importAudio(p.id,t.id,data),e=>e.status===422);assert.equal(s.get(p.id).tasks[0].state,'prepared');await s.importAudio(p.id,t.id,wav());await assert.rejects(s.importAudio(p.id,t.id,wav()),e=>e.status===409);assert.equal(s.get(p.id).tasks[0].source,'manual');await s.close();});
test('cancellation remains final even if a music tool returns audio later',async()=>{const entered=gate(),finish=gate(),s=await setup({minimax:{status:async()=>({available:true}),music:async()=>{entered.resolve();await finish.promise;return {data:wav()};}}}),p=await s.create({draft:draft()}),t=await music(s,p);await s.run(p.id,t.id);await entered.promise;await s.cancel(p.id,t.id);finish.resolve();await s.tail;assert.equal(s.get(p.id).tasks[0].state,'cancelled');await assert.rejects(s.audio(p.id,t.id),e=>e.status===409);await s.close();});
test('failed acceptance does not start a model and failed final persistence does not claim success',async()=>{let calls=0;const s=await setup({codex:{status:async()=>({ready:true}),generate:async()=>{calls++;return lyrics();}}}),p=await s.create({draft:draft()}),persist=s.persist.bind(s);s.persist=async()=>{throw Error('disk full');};await assert.rejects(s.prepare(p.id,{type:'lyrics',provider:'codex',revision:1,requestId:randomUUID()}));assert.equal(calls,0);assert.equal(s.get(p.id).tasks.length,0);s.persist=async p=>{if(p.tasks.some(t=>t.state==='succeeded'))throw Error('disk full');return persist(p);};await s.prepare(p.id,{type:'lyrics',provider:'codex',revision:1,requestId:randomUUID()});await s.tail;assert.equal(s.get(p.id).tasks[0].state,'interrupted');await s.close();});
test('restarting retains completed audio and interrupts unfinished work without resubmitting',async()=>{const s=await setup(),p=await s.create({draft:draft()}),t=await music(s,p);await s.importAudio(p.id,t.id,wav());const second=await music(s,s.get(p.id));const record=s.get(p.id);record.tasks.find(t=>t.id===second.id).state='running';await s.persist(record);await s.close();const restarted=await setup({directory:s.directory});assert.equal(restarted.get(p.id).tasks[0].state,'succeeded');assert.equal(restarted.get(p.id).tasks[1].state,'interrupted');await assert.rejects(restarted.run(p.id,second.id),e=>e.status===409);await restarted.close();});
test('unavailable models reject before creating work, while manual task preparation remains usable',async()=>{const s=await setup({codex:{status:async()=>({ready:false})},minimax:{status:async()=>({available:false})}}),p=await s.create({draft:draft()});await assert.rejects(s.prepare(p.id,{type:'lyrics',provider:'codex',revision:1,requestId:randomUUID()}),e=>e.status===503);const t=await music(s,p);await assert.rejects(s.run(p.id,t.id),e=>e.status===503);assert.equal(s.get(p.id).tasks[0].state,'prepared');await s.close();});
test('reviews attach to the exact completed audio and a favorite cannot be an unfinished task',async()=>{const s=await setup(),p=await s.create({draft:draft()}),t=await music(s,p);await assert.rejects(s.review(p.id,t.id,{emotion:'yes',naturalness:'yes',note:'test',favorite:true}));await s.importAudio(p.id,t.id,wav());const reviewed=await s.review(p.id,t.id,{emotion:'yes',naturalness:'no',note:'演唱需要调整',favorite:true});assert.equal(reviewed.favorite,t.id);assert.equal(reviewed.tasks[0].review.naturalness,'no');assert.equal((await s.review(p.id,t.id,{emotion:'yes',naturalness:'no',note:'复听',favorite:false})).favorite,null);await s.close();});
test('MiniMax runner uses documented stdin, bounded steps, smart permission and checks structured status',async()=>{const args=minimaxArguments({path:'C:/task with spaces',schema:'schema',output:'out',music:true});assert.ok(args.includes('--input'));assert.ok(args.includes('smart'));assert.ok(args.includes('15m'));assert.ok(!args.includes('full'));assert.ok(!args.includes('off'));const path=await mkdtemp(join(tmpdir(),'mcode-contract-')),m=new MiniMaxCode({run:async(command,args,{input})=>{assert.match(input,/创作/);await writeFile(args[args.indexOf('--output-last-message')+1],JSON.stringify(lyrics()));return {code:0,stdout:JSON.stringify({status:'succeeded'}),stderr:''};}});assert.deepEqual(await m.generate({path,prompt:'创作',schemaValue:{type:'object'}}),lyrics());const bad=new MiniMaxCode({run:async()=>({code:0,stdout:JSON.stringify({status:'failed'})})});await assert.rejects(bad.generate({path,prompt:'test',schemaValue:{}}),e=>e.status===502);});
test('MiniMax music completion requires matching task id, confined filename and actual audio bytes',async()=>{const s=await setup(),p=await s.create({draft:draft()}),t=await music(s,p),path=await mkdtemp(join(tmpdir(),'mcode-audio-'));const m=new MiniMaxCode();for(const report of [{taskId:'wrong',status:'completed',audioFile:'song.wav'},{taskId:t.id,status:'completed',audioFile:'../outside.wav'},{taskId:t.id,status:'unavailable',audioFile:''}]){m.generate=async()=>report;await assert.rejects(m.music({path,project:p,task:t}));}m.generate=async()=>({taskId:t.id,status:'completed',audioFile:'song.wav',note:'fixture'});await writeFile(join(path,'song.wav'),wav());assert.equal((await m.music({path,project:p,task:t})).audio.duration,2);await s.close();});
test('music audio is protected by origin checks and supports byte ranges, while credentials never appear in status',async()=>{const s=await setup(),p=await s.create({draft:draft()}),t=await music(s,p);await s.importAudio(p.id,t.id,wav());const server=createServer({root:resolve('dist'),service:{},studioService:s});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;try{const blocked=await fetch(base+'/api/studio/projects',{method:'POST',headers:{Origin:'https://evil.example','Content-Type':'application/json'},body:JSON.stringify({draft:draft()})});assert.equal(blocked.status,403);const response=await fetch(`${base}/api/studio/projects/${p.id}/tasks/${t.id}/audio`,{headers:{Range:'bytes=0-43'}});assert.equal(response.status,206);assert.equal((await response.arrayBuffer()).byteLength,44);assert.equal((await fetch(base+'/api/studio/status')).status,200);assert.equal((await fetch(base+'/api/studio/projects')).status,200);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));await s.close();}});
test('malformed lyric outputs cannot be accepted as drafts',()=>{for(const value of [null,{}, {title:'test',lyrics:'[Chorus]',direction:''},{title:'test',lyrics:'x'.repeat(7000),direction:'test'}])assert.throws(()=>validateLyricsOutput(value));assert.equal(inspectAudio(wav()).extension,'wav');});

test('MiniMax login failure is actionable without exposing execution logs',async()=>{const path=await mkdtemp(join(tmpdir(),'mcode-login-'));const m=new MiniMaxCode({run:async()=>({code:3,stdout:'',stderr:'mcode exec failed: Sign in to MiniMax to use Agent features. Run `mcode login`, then retry.'})});await assert.rejects(m.generate({path,prompt:'test',schemaValue:{}}),e=>e.status===503&&e.message.includes('尚未登录'));});
