import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { GenerationService } from '../server/generation-service.mjs';
import { createServer } from '../server/http.mjs';
import { ScoreService } from '../server/score-service.mjs';
import { CompositionService } from '../server/composition-service.mjs';
import { SongProjectService } from '../server/song-project-service.mjs';
import { PhrasingService } from '../server/phrasing-service.mjs';
import { ListeningService } from '../server/listening-service.mjs';
import { StudioService } from '../server/studio-service.mjs';
const directory = resolve(dirname(fileURLToPath(import.meta.url)), '..');
try { process.loadEnvFile(resolve(directory, '.env')); } catch (e) { if (e.code !== 'ENOENT') throw e; }
const service = await new GenerationService({ directory: resolve(directory, '.local/generations'), apiKey: process.env.ELEVENLABS_API_KEY || '', model: process.env.SONARA_MUSIC_MODEL || 'music_v2_5' }).init();
const scoreService=await new ScoreService({root:directory}).init();
const compositionService=await new CompositionService({root:directory}).init();
const studioService=await new StudioService({directory:resolve(directory,'.local/studio'),codex:compositionService.composer}).init();
const songProjectService=await new SongProjectService({root:directory}).init();
const phrasingService=await new PhrasingService({root:directory,project:songProjectService,composer:compositionService.composer,connection:compositionService.connection}).init();
const listeningService=await new ListeningService({root:directory,trialDirectory:resolve(directory,'dist/phrasing-trial')}).init();
const server = createServer({ root: resolve(directory, 'dist'), service, studioService, scoreService, compositionService, songProjectService, phrasingService, listeningService });
const port = Number(process.env.SONARA_PORT || 4173);
server.listen(port, '127.0.0.1', () => console.log(`Local: http://127.0.0.1:${port} · Codex ${compositionService.connection.ready?'ready':'unavailable'} · Online music ${service.status().configured ? 'configured, unverified' : 'not configured'}`));
for (const signal of ['SIGINT', 'SIGTERM']) process.once(signal, async () => { server.close(); await Promise.allSettled([service.close(),studioService.close(),scoreService.close(),compositionService.close(),songProjectService.close(),phrasingService.close(),listeningService.close()]); process.exit(0); });
